#include "AnalysisModel.hpp"
#include <sstream>
#include <iomanip>

namespace FEA {

std::string AnalysisModel::toInpString() const {
    std::stringstream ss;
    ss << "** CalculiX Input File generated by Structural FEA Suite\n";
    
    // Find maximum original node ID
    int maxNodeId = 0;
    for (const auto& pair : nodes) {
        if (pair.first > maxNodeId) maxNodeId = pair.first;
    }
    int nextNodeId = maxNodeId + 1;
    int nextElemId = 1;

    std::stringstream nodesStream;
    // 1. Write original user nodes
    for (const auto& pair : nodes) {
        const Node& n = pair.second;
        nodesStream << n.id << ", " << std::fixed << std::setprecision(6) 
                    << n.x << ", " << n.y << ", " << n.z << "\n";
    }

    std::stringstream elementsStream;
    std::vector<int> allElementIds;

    // Elements
    for (const auto& pair : elements) {
        const Element& e = pair.second;
        std::string elset = e.elset.empty() ? ("E" + std::to_string(e.id)) : e.elset;

        int eid = e.id > 0 ? e.id : nextElemId++;
        elementsStream << "*ELEMENT, TYPE=" << e.type << ", ELSET=" << elset << "\n";
        elementsStream << eid << ", ";
        for (size_t i = 0; i < e.nodeIds.size(); ++i) {
            elementsStream << e.nodeIds[i] << (i == e.nodeIds.size() - 1 ? "" : ", ");
        }
        elementsStream << "\n";
        allElementIds.push_back(eid);
    }

    // Nodes
    ss << "*NODE, NSET=NALL\n";
    ss << nodesStream.str();

    // Elements
    ss << elementsStream.str();

    // Define Eall element set containing all elements for post-processing/print requests
    if (!allElementIds.empty()) {
        ss << "*ELSET, ELSET=Eall\n";
        for (size_t i = 0; i < allElementIds.size(); ++i) {
            ss << allElementIds[i] << (i % 10 == 9 || i == allElementIds.size() - 1 ? "" : ", ");
            if (i % 10 == 9 && i != allElementIds.size() - 1) {
                ss << "\n";
            }
        }
        ss << "\n";
    }

    auto cleanName = [](const std::string& str) -> std::string {
        if (str.empty()) return "DEFAULT";
        std::string out = str;
        for (char& c : out) {
            if (!isalnum(c) && c != '_') c = '_';
        }
        return out;
    };

    // Materials
    for (const auto& mat : materials) {
        ss << "*MATERIAL, NAME=" << cleanName(mat.name) << "\n";
        ss << "*ELASTIC\n";
        ss << mat.youngModulus << ", " << mat.poissonRatio << "\n";
        ss << "*DENSITY\n";
        ss << mat.density << "\n";
    }

    // Sections (Mixed Modeling Support)
    for (const auto& sec : sections) {
        std::string cElset = cleanName(sec.elset);
        std::string cMat = cleanName(sec.material);
        if (sec.type == "SOLID") {
            ss << "*SOLID SECTION, ELSET=" << cElset << ", MATERIAL=" << cMat << "\n";
        } else if (sec.type == "BEAM") {
            ss << "*BEAM SECTION, ELSET=" << cElset << ", MATERIAL=" << cMat << ", SECTION=RECT\n";
            for (size_t i = 0; i < sec.params.size(); ++i) {
                ss << sec.params[i] << (i == sec.params.size() - 1 ? "" : ", ");
            }
            ss << "\n";
            ss << "0, 0, -1\n"; // Normal perpendicular to XY plane for 2D/3D frames
        } else if (sec.type == "SHELL" || sec.type == "PLATE") {
            ss << "*SHELL SECTION, ELSET=" << cElset << ", MATERIAL=" << cMat << "\n";
            if (!sec.params.empty()) {
                ss << sec.params[0] << "\n";
            } else {
                ss << "0.15\n"; // Default 15cm thickness
            }
        } else if (sec.type == "PLANE_STRESS" || sec.type == "PLANE_STRAIN" || sec.type == "MEMBRANE") {
            ss << "*SOLID SECTION, ELSET=" << cElset << ", MATERIAL=" << cMat << "\n";
            if (!sec.params.empty()) {
                ss << sec.params[0] << "\n";
            } else {
                ss << "0.20\n"; // Default 20cm thickness
            }
        }
    }

    // Boundary Conditions
    ss << "*STEP\n*STATIC\n";
    ss << "*BOUNDARY\n";
    for (const auto& bc : constraints) {
        for (int dof : bc.dofs) {
            ss << bc.nodeId << ", " << dof << ", " << dof << ", " << bc.value << "\n";
        }
    }

    // Loads
    ss << "*CLOAD\n";
    for (const auto& load : loads) {
        if (load.fx != 0) ss << load.nodeId << ", 1, " << load.fx << "\n";
        if (load.fy != 0) ss << load.nodeId << ", 2, " << load.fy << "\n";
        if (load.fz != 0) ss << load.nodeId << ", 3, " << load.fz << "\n";
    }

    bool hasBeams = false;
    bool hasNonBeams = false;
    for (const auto& sec : sections) {
        if (sec.type == "BEAM") hasBeams = true;
        else hasNonBeams = true;
    }

    if (hasBeams && !hasNonBeams) {
        ss << "*NODE FILE, OUTPUT=2D\nU\n";
        ss << "*EL FILE, SECTION FORCES, OUTPUT=2D\nS\n";
    } else {
        ss << "*NODE FILE\nU\n";
        ss << "*EL FILE\nS\n";
    }

    // Results in .dat file for DatParser (Displacements)
    ss << "*NODE PRINT, NSET=NALL\nU\n";
    ss << "*END STEP\n";

    return ss.str();
}

std::string AnalysisModel::toJson() const {
    nlohmann::json j;
    
    // Nodes
    for (const auto& pair : nodes) {
        const Node& n = pair.second;
        j["nodes"].push_back({{"id", n.id}, {"x", n.x}, {"y", n.y}, {"z", n.z}});
    }

    // Elements
    for (const auto& pair : elements) {
        const Element& e = pair.second;
        j["elements"].push_back({{"id", e.id}, {"type", e.type}, {"elset", e.elset}, {"nodes", e.nodeIds}});
    }

    // Materials
    for (const auto& mat : materials) {
        j["materials"].push_back({
            {"name", mat.name},
            {"youngModulus", mat.youngModulus},
            {"poissonRatio", mat.poissonRatio},
            {"density", mat.density}
        });
    }

    // Sections
    for (const auto& sec : sections) {
        j["sections"].push_back({
            {"elset", sec.elset},
            {"type", sec.type},
            {"material", sec.material},
            {"params", sec.params}
        });
    }

    // Constraints
    for (const auto& bc : constraints) {
        j["constraints"].push_back({{"nodeId", bc.nodeId}, {"dofs", bc.dofs}, {"value", bc.value}});
    }

    // Loads
    for (const auto& load : loads) {
        j["loads"].push_back({{"nodeId", load.nodeId}, {"fx", load.fx}, {"fy", load.fy}, {"fz", load.fz}});
    }

    return j.dump();
}

void AnalysisModel::fromJson(const std::string& jsonStr) {
    auto j = nlohmann::json::parse(jsonStr);
    clear();

    if (j.contains("nodes")) {
        for (const auto& item : j["nodes"]) {
            Node n;
            n.id = item["id"];
            n.x = item["x"];
            n.y = item["y"];
            n.z = item["z"];
            nodes[n.id] = n;
        }
    }

    if (j.contains("elements")) {
        for (const auto& item : j["elements"]) {
            Element e;
            e.id = item["id"];
            e.type = item["type"];
            e.elset = item.value("elset", "");
            e.nodeIds = item["nodes"].get<std::vector<int>>();
            elements[e.id] = e;
        }
    }

    if (j.contains("materials")) {
        for (const auto& item : j["materials"]) {
            Material m;
            m.name = item["name"];
            m.youngModulus = item["youngModulus"];
            m.poissonRatio = item["poissonRatio"];
            m.density = item["density"];
            materials.push_back(m);
        }
    }

    if (j.contains("sections")) {
        for (const auto& item : j["sections"]) {
            Section s;
            s.elset = item["elset"];
            s.type = item["type"];
            s.material = item["material"];
            s.params = item["params"].get<std::vector<double>>();
            sections.push_back(s);
        }
    }

    if (j.contains("constraints")) {
        for (const auto& item : j["constraints"]) {
            BoundaryCondition bc;
            bc.nodeId = item["nodeId"];
            bc.dofs = item["dofs"].get<std::vector<int>>();
            bc.value = item["value"];
            constraints.push_back(bc);
        }
    }

    if (j.contains("loads")) {
        for (const auto& item : j["loads"]) {
            Load l;
            l.nodeId = item["nodeId"];
            l.fx = item["fx"];
            l.fy = item["fy"];
            l.fz = item["fz"];
            loads.push_back(l);
        }
    }
}

} // namespace FEA
