#include "AnalysisModel.hpp"
#include <sstream>
#include <iomanip>

namespace FEA {

std::string AnalysisModel::toInpString() const {
    std::stringstream ss;
    ss << "** CalculiX Input File generated by Structural FEA Suite\n";
    
    // Nodes
    ss << "*NODE, NSET=NALL\n";
    for (const auto& pair : nodes) {
        const Node& n = pair.second;
        ss << n.id << ", " << std::fixed << std::setprecision(6) 
           << n.x << ", " << n.y << ", " << n.z << "\n";
    }

    // Elements (simplified for prototype)
    for (const auto& pair : elements) {
        const Element& e = pair.second;
        ss << "*ELEMENT, TYPE=" << e.type << ", ELSET=" << (e.elset.empty() ? ("E" + std::to_string(e.id)) : e.elset) << "\n";
        ss << e.id << ", ";
        for (size_t i = 0; i < e.nodeIds.size(); ++i) {
            ss << e.nodeIds[i] << (i == e.nodeIds.size() - 1 ? "" : ", ");
        }
        ss << "\n";
    }

    // Materials
    for (const auto& mat : materials) {
        ss << "*MATERIAL, NAME=" << mat.name << "\n";
        ss << "*ELASTIC\n";
        ss << mat.youngModulus << ", " << mat.poissonRatio << "\n";
        ss << "*DENSITY\n";
        ss << mat.density << "\n";
    }

    // Sections (Mixed Modeling Support)
    for (const auto& sec : sections) {
        if (sec.type == "SOLID") {
            ss << "*SOLID SECTION, ELSET=" << sec.elset << ", MATERIAL=" << sec.material << "\n";
        } else if (sec.type == "BEAM") {
            ss << "*BEAM SECTION, ELSET=" << sec.elset << ", MATERIAL=" << sec.material << ", SECTION=RECT\n";
            for (size_t i = 0; i < sec.params.size(); ++i) {
                ss << sec.params[i] << (i == sec.params.size() - 1 ? "" : ", ");
            }
            ss << "\n";
            ss << "0, 1, 0\n"; // Default orientation
        }
    }

    // Boundary Conditions
    ss << "*STEP\n*STATIC\n";
    ss << "*BOUNDARY\n";
    for (const auto& bc : constraints) {
        for (int dof : bc.dofs) {
            ss << bc.nodeId << ", " << dof << ", " << dof << ", " << bc.value << "\n";
        }
    }

    // Loads
    ss << "*CLOAD\n";
    for (const auto& load : loads) {
        if (load.fx != 0) ss << load.nodeId << ", 1, " << load.fx << "\n";
        if (load.fy != 0) ss << load.nodeId << ", 2, " << load.fy << "\n";
        if (load.fz != 0) ss << load.nodeId << ", 3, " << load.fz << "\n";
    }

    ss << "*NODE FILE\nU\n";
    ss << "*EL FILE\nS, E\n";

    // Results in .dat file for DatParser
    ss << "*NODE PRINT, NSET=NALL\nU\n";
    ss << "*SECTION PRINT, ELSET=Eall\nSOF, SOM\n";

    ss << "*END STEP\n";

    return ss.str();
}

std::string AnalysisModel::toJson() const {
    nlohmann::json j;
    
    // Nodes
    for (const auto& pair : nodes) {
        const Node& n = pair.second;
        j["nodes"].push_back({{"id", n.id}, {"x", n.x}, {"y", n.y}, {"z", n.z}});
    }

    // Elements
    for (const auto& pair : elements) {
        const Element& e = pair.second;
        j["elements"].push_back({{"id", e.id}, {"type", e.type}, {"elset", e.elset}, {"nodes", e.nodeIds}});
    }

    // Materials
    for (const auto& mat : materials) {
        j["materials"].push_back({
            {"name", mat.name},
            {"youngModulus", mat.youngModulus},
            {"poissonRatio", mat.poissonRatio},
            {"density", mat.density}
        });
    }

    // Sections
    for (const auto& sec : sections) {
        j["sections"].push_back({
            {"elset", sec.elset},
            {"type", sec.type},
            {"material", sec.material},
            {"params", sec.params}
        });
    }

    // Constraints
    for (const auto& bc : constraints) {
        j["constraints"].push_back({{"nodeId", bc.nodeId}, {"dofs", bc.dofs}, {"value", bc.value}});
    }

    // Loads
    for (const auto& load : loads) {
        j["loads"].push_back({{"nodeId", load.nodeId}, {"fx", load.fx}, {"fy", load.fy}, {"fz", load.fz}});
    }

    return j.dump();
}

void AnalysisModel::fromJson(const std::string& jsonStr) {
    auto j = nlohmann::json::parse(jsonStr);
    clear();

    if (j.contains("nodes")) {
        for (const auto& item : j["nodes"]) {
            Node n;
            n.id = item["id"];
            n.x = item["x"];
            n.y = item["y"];
            n.z = item["z"];
            nodes[n.id] = n;
        }
    }

    if (j.contains("elements")) {
        for (const auto& item : j["elements"]) {
            Element e;
            e.id = item["id"];
            e.type = item["type"];
            e.elset = item.value("elset", "");
            e.nodeIds = item["nodes"].get<std::vector<int>>();
            elements[e.id] = e;
        }
    }

    if (j.contains("materials")) {
        for (const auto& item : j["materials"]) {
            Material m;
            m.name = item["name"];
            m.youngModulus = item["youngModulus"];
            m.poissonRatio = item["poissonRatio"];
            m.density = item["density"];
            materials.push_back(m);
        }
    }

    if (j.contains("sections")) {
        for (const auto& item : j["sections"]) {
            Section s;
            s.elset = item["elset"];
            s.type = item["type"];
            s.material = item["material"];
            s.params = item["params"].get<std::vector<double>>();
            sections.push_back(s);
        }
    }

    if (j.contains("constraints")) {
        for (const auto& item : j["constraints"]) {
            BoundaryCondition bc;
            bc.nodeId = item["nodeId"];
            bc.dofs = item["dofs"].get<std::vector<int>>();
            bc.value = item["value"];
            constraints.push_back(bc);
        }
    }

    if (j.contains("loads")) {
        for (const auto& item : j["loads"]) {
            Load l;
            l.nodeId = item["nodeId"];
            l.fx = item["fx"];
            l.fy = item["fy"];
            l.fz = item["fz"];
            loads.push_back(l);
        }
    }
}

} // namespace FEA
