package com.diamon.civil.engine;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.io.File;
import java.io.FileOutputStream;
import java.util.List;

/**
 * D2: ReportGenerator — Generates a professional PDF report using iText7.
 */
public class ReportGenerator {

    public static boolean generateReport(File outFile, String title, String summary, List<DatParser.SectionForces> forces) {
        try {
            PdfWriter writer = new PdfWriter(new FileOutputStream(outFile));
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);

            // Title
            Paragraph pTitle = new Paragraph(title)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(24)
                    .setBold();
            document.add(pTitle);

            // Summary
            document.add(new Paragraph("Structural Analysis Summary")
                    .setBold()
                    .setFontSize(14)
                    .setMarginTop(20));
            document.add(new Paragraph(summary));

            // Results Table
            if (forces != null && !forces.isEmpty()) {
                document.add(new Paragraph("Section Forces Results")
                        .setBold()
                        .setFontSize(14)
                        .setMarginTop(20));

                Table table = new Table(UnitValue.createPointArray(new float[]{60, 60, 80, 80, 80, 80, 80}))
                        .useAllAvailableWidth();

                // Header
                table.addHeaderCell(new Cell().add(new Paragraph("Elem ID").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("Int Pt").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("N [N]").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("V2 [N]").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("V3 [N]").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("M1 [N·m]").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("M2 [N·m]").setBold()));

                // Rows
                for (DatParser.SectionForces sf : forces) {
                    table.addCell(new Cell().add(new Paragraph(String.valueOf(sf.elementId))));
                    table.addCell(new Cell().add(new Paragraph(String.valueOf(sf.integrationPoint))));
                    table.addCell(new Cell().add(new Paragraph(String.format("%.2f", sf.N))));
                    table.addCell(new Cell().add(new Paragraph(String.format("%.2f", sf.V2))));
                    table.addCell(new Cell().add(new Paragraph(String.format("%.2f", sf.V3))));
                    table.addCell(new Cell().add(new Paragraph(String.format("%.2f", sf.M1))));
                    table.addCell(new Cell().add(new Paragraph(String.format("%.2f", sf.M2))));
                }

                document.add(table);
            }

            // Footer
            document.add(new Paragraph("\nGenerated by FEA Suite Android")
                    .setTextAlignment(TextAlignment.RIGHT)
                    .setFontSize(10)
                    .setFontColor(ColorConstants.GRAY));

            document.close();
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
